# Generated by Django 5.1.3 on 2025-01-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kursy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kurs', models.CharField(max_length=20)),
                ('poSpisku', models.CharField(max_length=10)),
                ('naLitso', models.CharField(max_length=10)),
                ('naryad', models.CharField(max_length=10)),
                ('bolnye', models.CharField(max_length=10)),
                ('uvolnenie', models.CharField(max_length=10)),
                ('otpusk', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Расход Курса',
                'verbose_name_plural': 'Расход курсов',
            },
        ),
    ]
