# Generated by Django 5.1.3 on 2025-01-27 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_naryads'),
    ]

    operations = [
        migrations.CreateModel(
            name='bolnyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_of_bolnyes', models.CharField(max_length=255)),
                ('Kursy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursy')),
            ],
        ),
        migrations.CreateModel(
            name='otpusks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_of_otpusks', models.CharField(max_length=255)),
                ('Kursy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursy')),
            ],
        ),
        migrations.CreateModel(
            name='uvolnenies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_of_uvolnenies', models.CharField(max_length=255)),
                ('Kursy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kursy')),
            ],
        ),
    ]
