# Generated by Django 5.1.3 on 2025-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bolnyes_otpusks_uvolnenies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kursy',
            options={'ordering': ['name_kurs'], 'verbose_name': 'Расход Курса', 'verbose_name_plural': 'Расход курсов'},
        ),
        migrations.RemoveField(
            model_name='kursy',
            name='id',
        ),
        migrations.AlterField(
            model_name='kursy',
            name='name_kurs',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
