# Generated by Django 5.1.3 on 2025-01-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_kursy_options_remove_kursy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolnyes',
            name='Kursy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolnyes', to='main.kursy'),
        ),
        migrations.AlterField(
            model_name='naryads',
            name='Kursy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naryads', to='main.kursy'),
        ),
        migrations.AlterField(
            model_name='otpusks',
            name='Kursy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otpusks', to='main.kursy'),
        ),
        migrations.AlterField(
            model_name='uvolnenies',
            name='Kursy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uvolnenies', to='main.kursy'),
        ),
    ]
