# Generated by Django 5.1.3 on 2025-01-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_bolnyes_kursy_alter_naryads_kursy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_10',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_11',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_12',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_13',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_14',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_15',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_16',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_17',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_18',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_19',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_20',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_21',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_22',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_23',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_24',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_25',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_26',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_27',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_28',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_29',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_30',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_31',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_32',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_33',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_34',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_35',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_36',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_37',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_38',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_39',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_40',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_6',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_7',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_8',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='information_of_bolnyes_9',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
