# Generated by Django 5.1.3 on 2025-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bolnyes_information_of_bolnyes_10_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolnyes',
            options={'verbose_name': 'Больные Курса', 'verbose_name_plural': 'Больные курсов'},
        ),
        migrations.AlterModelOptions(
            name='kursy',
            options={'ordering': ['name_kurs'], 'verbose_name': 'Расход Курса', 'verbose_name_plural': 'а-Расход курсов'},
        ),
        migrations.AlterModelOptions(
            name='naryads',
            options={'verbose_name': 'Наряды Курса', 'verbose_name_plural': 'Наряды курсов'},
        ),
        migrations.AlterModelOptions(
            name='otpusks',
            options={'verbose_name': 'Отпуск Курса', 'verbose_name_plural': 'Отпуск курсов'},
        ),
        migrations.AlterModelOptions(
            name='uvolnenies',
            options={'verbose_name': 'Увольняемые Курса', 'verbose_name_plural': 'Увольняемые курсов'},
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_17',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_18',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_19',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_20',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_21',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_22',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_23',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_24',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_25',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_26',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_27',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_28',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_29',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_30',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_31',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_32',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_33',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_34',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_35',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_36',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_37',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_38',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_39',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_40',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='information_of_uvolnenies_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_17',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_18',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_19',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_20',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_21',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_22',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_23',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_24',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_25',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_26',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_27',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_28',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_29',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_30',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_31',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_32',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_33',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_34',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_35',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_36',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_37',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_38',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_39',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_40',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bolnyes',
            name='information_of_bolnyes_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='uvolnenies',
            name='information_of_uvolnenies',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
