# Generated by Django 5.1.3 on 2025-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bolnyes_options_alter_kursy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_10',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_11',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_12',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_13',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_14',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_15',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_16',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_17',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_18',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_19',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_20',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_21',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_22',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_23',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_24',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_25',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_26',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_27',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_28',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_29',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_30',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_31',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_32',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_33',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_34',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_35',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_36',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_37',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_38',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_39',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_40',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_6',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_7',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_8',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='information_of_otpusks_9',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='otpusks',
            name='information_of_otpusks',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
