# Generated by Django 5.1.3 on 2025-02-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_naryads_information_of_naryads_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_10_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_10_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_11_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_11_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_12_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_12_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_13_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_13_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_14_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_14_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_15_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_15_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_16_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_16_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_17_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_17_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_18_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_18_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_19_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_19_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_20_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_20_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_21_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_21_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_22_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_22_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_23_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_23_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_24_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_24_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_25_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_25_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_26_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_26_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_27_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_27_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_28_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_28_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_29_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_29_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_2_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_2_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_30_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_30_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_31_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_31_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_32_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_32_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_33_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_33_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_34_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_34_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_35_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_35_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_36_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_36_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_37_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_37_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_38_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_38_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_39_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_39_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_3_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_3_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_40_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_40_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_4_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_4_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_5_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_5_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_6_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_6_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_7_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_7_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_8_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_8_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_9_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_9_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='naryads',
            name='info_of_naryads_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
