# Generated by Django 5.1.3 on 2025-02-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_naryads_info_of_naryads_10_mesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_10_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_10_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_11_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_11_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_12_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_12_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_13_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_13_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_14_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_14_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_15_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_15_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_16_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_16_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_17_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_17_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_18_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_18_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_19_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_19_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_20_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_20_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_21_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_21_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_22_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_22_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_23_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_23_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_24_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_24_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_25_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_25_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_26_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_26_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_27_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_27_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_28_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_28_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_29_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_29_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_2_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_2_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_30_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_30_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_31_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_31_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_32_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_32_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_33_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_33_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_34_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_34_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_35_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_35_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_36_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_36_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_37_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_37_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_38_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_38_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_39_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_39_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_3_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_3_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_40_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_40_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_4_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_4_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_5_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_5_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_6_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_6_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_7_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_7_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_8_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_8_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_9_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_9_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='bolnyes',
            name='info_of_bolnyes_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
