# Generated by Django 5.1.3 on 2025-02-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_bolnyes_info_of_bolnyes_10_mesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_10_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_10_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_11_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_11_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_12_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_12_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_13_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_13_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_14_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_14_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_15_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_15_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_16_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_16_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_17_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_17_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_18_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_18_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_19_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_19_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_20_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_20_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_21_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_21_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_22_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_22_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_23_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_23_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_24_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_24_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_25_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_25_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_26_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_26_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_27_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_27_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_28_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_28_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_29_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_29_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_2_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_2_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_30_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_30_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_31_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_31_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_32_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_32_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_33_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_33_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_34_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_34_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_35_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_35_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_36_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_36_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_37_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_37_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_38_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_38_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_39_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_39_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_3_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_3_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_40_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_40_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_4_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_4_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_5_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_5_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_6_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_6_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_7_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_7_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_8_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_8_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_9_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_9_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='info_of_otpusks_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_10_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_10_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_11_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_11_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_12_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_12_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_13_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_13_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_14_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_14_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_15_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_15_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_16_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_16_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_17_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_17_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_18_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_18_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_19_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_19_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_20_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_20_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_21_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_21_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_22_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_22_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_23_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_23_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_24_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_24_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_25_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_25_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_26_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_26_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_27_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_27_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_28_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_28_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_29_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_29_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_2_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_2_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_30_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_30_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_31_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_31_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_32_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_32_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_33_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_33_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_34_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_34_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_35_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_35_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_36_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_36_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_37_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_37_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_38_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_38_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_39_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_39_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_3_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_3_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_40_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_40_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_4_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_4_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_5_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_5_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_6_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_6_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_7_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_7_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_8_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_8_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_9_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_9_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_mesto',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='info_of_uvolnenies_vremya',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
