# Generated by Django 5.1.3 on 2025-02-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_kursy_bolnye_alter_kursy_nalitso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursy',
            name='bolnye',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kursy',
            name='naLitso',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kursy',
            name='naryad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kursy',
            name='otpusk',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kursy',
            name='poSpisku',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kursy',
            name='uvolnenie',
            field=models.IntegerField(default=0),
        ),
    ]
