# Generated by Django 5.1.3 on 2025-02-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_kursy_bolnye_alter_kursy_nalitso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolnyes',
            name='Kursy',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='bolnyes', to='main.kursy'),
        ),
    ]
