# Generated by Django 5.1.3 on 2025-02-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_bolnyes_kursy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursy',
            name='name_kurs',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
