# Generated by Django 5.1.3 on 2025-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_kursy_name_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursy',
            name='name_kurs',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
