# Generated by Django 5.1.3 on 2025-02-06 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_kursy_name_kurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolnyes',
            name='Kursy',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='main.kursy'),
        ),
    ]
