# Generated by Django 5.1.3 on 2025-02-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_bolnyes_kursy'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolnyes',
            name='Kursy',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kursy'),
        ),
    ]
