# Generated by Django 5.1.3 on 2025-02-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_bolnyes_kursy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naryads',
            name='Kursy',
        ),
        migrations.RemoveField(
            model_name='otpusks',
            name='Kursy',
        ),
        migrations.RemoveField(
            model_name='uvolnenies',
            name='Kursy',
        ),
    ]
