# Generated by Django 5.1.3 on 2025-02-06 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_naryads_kursy_remove_otpusks_kursy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naryads',
            name='Kursy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naryads', to='main.kursy'),
        ),
        migrations.AddField(
            model_name='otpusks',
            name='Kursy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otpusks', to='main.kursy'),
        ),
        migrations.AddField(
            model_name='uvolnenies',
            name='Kursy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uvolnenies', to='main.kursy'),
        ),
    ]
