# Generated by Django 5.1.3 on 2025-01-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
