# Generated by Django 5.1.3 on 2025-01-24 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authin', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
