# Generated by Django 5.1.3 on 2025-01-25 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authin', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
