# Generated by Django 5.1.3 on 2025-01-27 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authin', '0005_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
